server:
  port: 8082

spring:
  security:
    oauth2:
      #this is using oauth2ResourceServer { jwt {  } }
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/landonline
#          jwk-set-uri: http://localhost:8080/realms/landonline/protocol/openid-connect/certs

      client:
        registration:
          search-service-b:
            provider: keycloak
            client-id: search-service-b
            client-secret: another_secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/landonline
#            authorization-uri: http://localhost:8080/realms/landonline/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/realms/landonline/protocol/openid-connect/token
#            user-info-uri: http://localhost:8080/realms/landonline/protocol/openid-connect/userinfo
